# Generated by Django 5.2.4 on 2025-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('beds', models.IntegerField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مشغولة'), ('cleaning', 'تحتاج تنظيف'), ('maintenance', 'قيد الصيانة')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('facilities', models.CharField(max_length=100)),
            ],
        ),
    ]
